### ISSUE TITLE
Adding Navbar

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Global_Weather#1]

**Comment by rhinoxD** [comment]
!assign

**Comment by rhinoxD** [comment]
What all would you like to have in the navbar?
Is this style ok?

![image](https://user-images.githubusercontent.com/86461976/207048462-32b1f82e-9c62-43df-89d4-4d468cfbaa27.png)

**Comment by Kritika30032002** [comment]
Categories for?

**Comment by rhinoxD** [comment]
It's just a sample. For now I could add other links in the categories if you want or else I could remove it. Your call.

**Comment by Kritika30032002** [comment]
I just want to know your ideas of navbar? like what what links can we add to this weather project.

**Comment by rhinoxD** [comment]
See I think that there's no need for a navbar for this app as a weather application only requires a search bar on a card component. But if you really want a navbar then we could obviously add the logo(far left), about and contact. As for signin, I don't think so users would want to signin to a webapp just to know the weather. So it's up to you now, whatever you say...

**Comment by Kritika30032002** [comment]
Home , about

For now add these two

**Comment by Kritika30032002** [comment]
with logo

**Comment by rhinoxD** [comment]
You also wanted a dark/light mode right? I could also add that in the navbar if you want?

**Comment by Kritika30032002** [comment]
I can be added as another contribution. As it is already assigned. If he/she does not complete that then u can get that issue assigned

**Comment by rhinoxD** [comment]
So for now just a navbar?

**Comment by Kritika30032002** [comment]
yes
