### ISSUE TITLE
Integrate Backend with Front-end

### ISSUE THREAD

**Issue by saurabhbakolia** [Kritika30032002/Global_Weather#12]
###  Fetching data form Weather API and integrating backend with front-end

**Comment by saurabhbakolia** [comment]
@Kritika30032002  assign this issue to me.

**Comment by saurabhbakolia** [comment]
Done with the work. Have you any suggestions?
Can I make a new PR.

**Comment by Kritika30032002** [comment]
show me video of what u have done

**Comment by saurabhbakolia** [comment]
![Weather App](https://user-images.githubusercontent.com/78996216/210125817-341ab0b6-a289-4823-9710-0b44aa1bc857.gif)

I have done this so far. And working on performance and error handling. 
@Kritika30032002 ,am creating  a new PR for this.
