### ISSUE TITLE
Improving UI/UX 

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Global_Weather#3]
Currently the project does not contain any CSS. Only login has been applied to get desired results.

So you can design the Project page adding styling to it.

**Comment by saurabhbakolia** [comment]
Hi, @Kritika30032002  is there anyone working on UI/UX. 
If you have any UI Design then I can work on this.

**Comment by Kritika30032002** [comment]
are u working? @saurabhbakolia

**Comment by saurabhbakolia** [comment]
Yes, I am working.

**Comment by Kritika30032002** [comment]
okay
