### ISSUE TITLE
Adding Light/Dark Mode

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Global_Weather#4]

**Comment by musavveer** [comment]
I will work on this issue.

**Comment by musavveer** [comment]
Website currently doesn't contain any content!! 
Where should the Button be placed?

<img width="1440" alt="Screenshot 2022-12-11 at 10 32 02 AM" src="https://user-images.githubusercontent.com/62888562/206887375-2871480d-e063-41a7-9bc2-919a3901b2b4.png">

**Comment by Kritika30032002** [comment]
Firstly website need some styling  then only this feature can be implemented

**Comment by musavveer** [comment]
Ok Then I will wait!!

**Comment by lata-11** [comment]
Assign me this issue please ma'am.

**Comment by Kritika30032002** [comment]
@musavveer  You can now proceed!

**Comment by Pritam1136** [comment]
You can assign this issue to me .

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue
